# vim: set expandtab ts=2:
language: cpp
compiler:
- gcc
- clang
sudo: false
script:
- mkdir out
- cd out
- cmake ..
- make
install:
- test "$CXX" != g++ || export CXX="g++-4.8" CC="gcc-4.8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - clang
    - libsdl2-dev
